-- Create a test user and grant privileges
CREATE USER testuser IDENTIFIED BY testpwd;
GRANT CONNECT, RESOURCE TO testuser;

-- Create a sample table
CREATE TABLE testuser.sample_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50),
    created_at DATE DEFAULT SYSDATE
);

-- Insert sample rows
INSERT INTO testuser.sample_table (name) VALUES ('Hello from Oracle Free 26ai');
INSERT INTO testuser.sample_table (name) VALUES ('Lite or Full, same SQL!');
INSERT INTO testuser.sample_table (name) VALUES ('Testing INSERT functionality');
INSERT INTO testuser.sample_table (name) VALUES ('Row four with timestamp');
INSERT INTO testuser.sample_table (name) VALUES ('Another entry for fun');
INSERT INTO testuser.sample_table (name) VALUES ('Final sample row');

-- Create a second table for joins
CREATE TABLE testuser.orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(50),
    amount NUMBER(10,2),
    order_date DATE DEFAULT SYSDATE
);

-- Insert sample orders
INSERT INTO testuser.orders (customer_name, amount) VALUES ('Alice', 120.50);
INSERT INTO testuser.orders (customer_name, amount) VALUES ('Bob', 75.00);
INSERT INTO testuser.orders (customer_name, amount) VALUES ('Charlie', 300.00);
INSERT INTO testuser.orders (customer_name, amount) VALUES ('Alice', 45.25);
INSERT INTO testuser.orders (customer_name, amount) VALUES ('Diana', 220.10);

-- Create a simple view
CREATE OR REPLACE VIEW testuser.customer_totals AS
SELECT customer_name, SUM(amount) AS total_spent
FROM testuser.orders
GROUP BY customer_name;

-- Commit changes
COMMIT;
